# Generated by Django 3.2.4 on 2021-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('opinion', models.TextField()),
                ('time_publish', models.DateTimeField()),
            ],
        ),
    ]
