# Generated by Django 3.2.4 on 2021-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='id_author',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
