# Generated by Django 3.2.4 on 2021-06-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_books', '0002_books_id_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField()),
                ('fullname', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('death', models.DateField(null=True)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='id_publisher',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='id_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_books.author'),
        ),
    ]
